apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: tekton-kn-sample-
spec:
  pipelineRef:
    name: "demo.pipeline"
  taskRunTemplate:
    serviceAccountName: "pipeline-account"
  taskRunSpecs:
    - pipelineTaskName: build-image
      computeResources:
        requests:
          cpu: 500m
          memory: 2Gi
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        metadata:
          annotations:
            csi.alibabacloud.com/mountpoint: "your-nas-endpoint"
        spec:
          accessModes:
            - ReadWriteMany
          storageClassName: alibaba-cloud-nas
          resources:
            requests:
              storage: 30Gi
    - name: docker-regcred
      secret:
        defaultMode: 420
        items:
          - key: .dockerconfigjson
            path: config.json
        secretName: docker-regcred
  params:
    - name: repo_url
      value: https://gitee.com/AliyunContainerService/tekton-demo.git
    - name: repo_revision
      value: main
    - name: image-registry
      value: 192.168.110.239:5000/acs-demo-ns
    - name: image-repo-name
      value: hello-world