apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: "demo.pipeline"
spec:
  params:
  - name: image-registry
    default: 192.168.110.239:5000
  - name: image-repo-name
    type: string
  - name: repo_url
    type: string
    default: 192.168.110.239:5000
  - name: repo_revision
    type: string
  workspaces:
  - name: git-source
  - name: docker-regcred
  tasks:
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
    - name: repo_url
      value: $(params.repo_url)
    - name: revision
      value: $(params.repo_revision)
    - name: deleteExisting
      value: "true"
    workspaces:
    - name: output
      workspace: git-source
  - name: build-image
    runAfter: [fetch-from-git]
    taskRef:
      name: kaniko
    params:
    - name: IMAGE
      value: $(params.image-registry)/$(params.image-repo-name):$(tasks.fetch-from-git.results.commit)
    - name: CONTEXT
      value: src
    - name: DOCKERFILE
      value: $(workspaces.source.path)/src/Dockerfile
    workspaces:
    - name: source
      workspace: git-source
    - name: dockerconfig
      workspace: docker-regcred